name: Gleam
description: Check Gleam Formatting

on:
  workflow_call:
    inputs:
      check-path:
        required: false
        type: string
        default: "."

jobs:
  format:
    name: Gleam
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup BEAM Environment
        uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Check Source Formatting
        run: gleam format --check ${{ inputs.check-path }}
