name: Markdown
description: Check Markdown Lint

on:
  workflow_call:
    inputs:
      markdownlint-version:
        required: false
        type: string
        default: "latest"

jobs:
  format:
    name: Markdown
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: latest

      - name: Lint Check
        run: npx markdownlint-cli2@${{ inputs.markdownlint-version }}
